### ISSUE TITLE
Consider literate README.org

### ISSUE THREAD

**Issue by yurrriq** [lfex/exemplar#13]
I love [org-mode][org-mode] and have had great success in using it for literate programming.

Since there are so many code snippets in [the README][README], it seems to me that rewriting it literally (:laughing:) would be of great benefit. With that we could tangle `example.lfe` etc.

What do you think, @oubiwann? I'm happy to do this, but not if you're wholly opposed.

[org-mode]: http://orgmode.org
[README]: https://github.com/lfex/exemplar/blob/master/README.md

**Comment by oubiwann** [comment]
I'm hesitant to do this; the benefit of .md is that so many people know it -- they can read it and make updates so easily. (The LFE projects originally had .rst files, but not enough people new ReST.)

I read through the features that org-mode provides ... but I'm still unclear what you would gain with regard to the code snippets? In what ways would this benefit? (this is my curiosity speaking!)

Also: thanks for all the recent updates/edits you've made!

**Comment by yurrriq** [comment]
`org-mode` would be beneficial on the dev/maintainer side. With "smart", literate source, it's way easier (for me, at least) to reason about. A good example is my Clojure solution to Exercism's Bob. (Will edit with link shortly) With `ox-gfm` (will edit and link)we could have our cake and eat it too.

**Comment by yurrriq** [comment]
[Here][1]'s the link I never posted. August was rough.. Ultimately :+1: for Markdown, but literate org-mode plus [`ox-gfm`][2] for .md output would be sweet.

[1]: https://github.com/yurrriq/exercism/tree/795813646f7880ca8ffa611c4e5026e94c7300e8/bob
[2]: https://github.com/larstvei/ox-gfm

**Comment by yurrriq** [comment]
Consider [LLFE](https://github.com/llfe/llfe) or scrapping the idea. LLFE doesn't offer the same in-buffer execution benefits as Org.
