### ISSUE TITLE
Put lodox dependency in a profile

### ISSUE THREAD

**Issue by yurrriq** [lfex/exemplar#16]
In upgrading from 0.3.0 to 0.3.2 I'm getting serious errors.

```
exception error: undef
  in (: exemplar-html-util make-html "meta" (charset "UTF-8"))
```

**Comment by yurrriq** [comment]
It seems there's something more rebar3-related at play here..

**Comment by yurrriq** [comment]
Hmm.. to avoid mutual dependency issues, it's probably best to put lodox in a profile, e.g. `doc`. I did that for levaindoc and it seems to be working well now.

**Comment by oubiwann** [comment]
Yup -- that's what I did too. I've started doing this with my other projects, too, but in order to diminish the number of downloads/steps/etc required to perform basic tasks. I'm digging it so far.

**Comment by oubiwann** [comment]
It sounds like you got it sorted out ... but just to be sure: all the local testing I did indicated that this wasn't a breaking change (unless you were calling directly to the util module) -- the API (all the defelem macro calls in the includes) didn't change.

Let me know if I've misunderstood your subsequent comments (if this is still a problem).

**Comment by yurrriq** [comment]
I reverted to exemplar 0.3.0 for now. Sleepy me couldn't resolve the issue any other way.

**Comment by oubiwann** [comment]
Yeah, I know that feeling (about late-night debugging) :-/

Let me know if you continue to see issues after a full clean/rm -rf _build/etc.

**Comment by oubiwann** [comment]
As for the topic of this ticket: I'll try out the latest release of lodox and let you know if I can put it back in a profile (the cyclic dep thing).

**Comment by yurrriq** [comment]
I never got to the root of it, but i suspect the issue is that exemplar has lodox (which depends on exemplar) as a project-level plugin--i.e. download when compiling exemplar as a dependency-- so my exemplar dependency was download an older copy of lodox, which was depending on an older version of exemplar and somehow at compile time, rebar3 was referencing some broken combination of .beam files... I'm mobile now, but you can see how I solved a similar issue on the latest levaindoc's rebar.config. Basically, I put `{plugins, [lodox]}` under a profile called `doc`, thereby preventing it's download when compiling levaindoc as a dependent, mostly importantly as a decency of lodox itself. I think we should do the same here (and for clj).


Let me know if that somehow makes sense :laughing:

**Comment by yurrriq** [comment]
See [my comment](https://github.com/rvirding/lfe/issues/201#issuecomment-198483351) on the LFE v1.0 Support issue. If you want I can make a PR soon.

**Comment by yurrriq** [comment]
New strategy: publish Hex packages for the major lfex repos and specify Lodox (Hex dep) as a `project_plugin`.

**Comment by yurrriq** [comment]
I have sorted this out and [published to Hex](https://hex.pm/packages/exemplar). :grin:

**Comment by yurrriq** [comment]
This is all good after tonight's hacking.
